repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-ast
  - id: flake8
    args: ['--config=setup.cfg']
  - id: fix-encoding-pragma
  - id: detect-private-key
